### ISSUE TITLE
Set option 'arm_64bit' in config.txt

### ISSUE THREAD

**Issue by legendlc** [s-matyukevich/raspberry-pi-os#158]
When I worked on lesson1, I installed Raspbian Buster(release date 2019-09-26). There are 3 kernel image under `boot` partition: `kernel.img`(32bit older RPI), `kernel7.img`(32bit RPI2&3) and `kernel7l.img`(32-bit RPI4). 

After I deleted `kernel7.img`, copy `kernel8.img`, modified `config.txt` according to the tutorial and boot my Pi 3b, no UART message was printed. However, when I deleted **all kernel\*.img** except kernel8.img, it worked. I searched the Internet for a while and couldn't figure out why. Maybe the latest firmware has changed the boot sequence?

Then I saw the `arm_64bit` option in the [official document](https://www.raspberrypi.org/documentation/configuration/config-txt/).

> arm_64bit
> 
> If set to non-zero, forces the kernel loading system to assume a 64-bit kernel, starts the processors up in 64-bit mode, and sets kernel8.img to be the kernel image loaded, unless there is an explicit kernel option defined in which case that is used instead. Defaults to 0 on all platforms. NOTE: 64-bit kernels must be uncompressed image files.
> 
> Note that the 64-bit kernel will only work on the Pi4, Pi3, and Pi2B rev1.2 boards **with latest firmware**.

I tried it and it worked well without deleting any other kernel*.img.  Maybe setting `arm_64bit` option is a better choice for current firmware?

**Comment by s-matyukevich** [comment]
Thanks, @legendlc for reporting this. 

I made a fix in [this](https://github.com/s-matyukevich/raspberry-pi-os/commit/677e22f0f49ad30ab840ba429b02b76718d6811f) commit.

I prefer to add instructions to delete all 'kernel*img' files rather than use the `arm_64bit` option because I am not sure how this option is going to work with different versions of Raspberry Pi boards as well as different firmware versions. Deleting all `kernel*.img` files looks like a more reliable way to me. Also, default config.txt is used in a lot of different places (source of all lessons, exercises, translations, etc) and updating all of them could be painful
