### ISSUE TITLE
Check whether the RPi OS can be successfully compiled and connected from Mac OS and Windows

### ISSUE THREAD

**Issue by s-matyukevich** [s-matyukevich/raspberry-pi-os#2]

**Comment by bl4ckout31** [comment]
I got Lesson01 working on Windows 10 Pro Version 1803 with a Prolific USB to TTL serial cable and PuTTY. The following environements worked for compiling: 

- Docker for Windows
- Docker Toolbox
- Windows Subsystem for Linux (Ubuntu)

**Comment by s-matyukevich** [comment]
Perfect, thanks @bl4ckout31 !

**Comment by evopen** [comment]
I'm currently using macOS 10.13.5. Latest Prolific driver is working fine on macOS. Compiler thing will work if one uses Docker environment.

But there is a shitty thing I must say. When I use screen for reading data via uart, like `screen /dev/cu.usbserial 115200`. Note that there is a device file which will only present while the cable is connected. Meaning I have to plug in the cable and execute screen command immediately to see the result. Otherwise those characters will just slip away.

**Comment by s-matyukevich** [comment]
@evopen it works in the same way on Linux too. I'll mention this in the Prerequisites and then close this issue.

**Comment by xesco** [comment]
This is a good observation as I was having the same problem: I could not see the "hello world" and I was trying to figure out what went wrong.

**Comment by bl4ckout31** [comment]
My workaround for this is to power the RPi with a micro-usb cable (which is the recommended way anyway) so I can keep the serial cable plugged all the time and use the same screen instance for entire sessions.

**Comment by s-matyukevich** [comment]
I [updated](https://github.com/s-matyukevich/raspberry-pi-os/commit/f4568e0ac459c089ac5b4fbbcfdaaa234264f8a7) prerequisites and added a link to this issue there.  Closing the issue now.
