### ISSUE TITLE
Is it possible to boot up raspberry-pi-os from Uboot?

### ISSUE THREAD

**Issue by imilk23** [s-matyukevich/raspberry-pi-os#236]
I want to use tftpboot instead of copying the binary to sdcard each lesson so I curious that is there someone trying to boot up raspberry-pi-os from Uboot?

**Comment by nicolasmesa** [comment]
@rhett511 , I created a project to boot via UART with a few changes to the kernel in this project. I wrote a [detailed blog post](https://blog.nicolasmesa.co/posts/2019/08/booting-your-own-kernel-on-raspberry-pi-via-uart/) on what I did and mistakes I made along the way. I've made a few improvements since then. Feel free to take a look at the [source](https://github.com/nicolasmesa/PiOS/tree/master).

I hope this helps.

**Comment by imilk23** [comment]
Hi @nicolasmesa,
Thank you for responding to me.
However, I want to use u-boot instead of writing my own bootloader code.

I found the answer to this question. 
U-boot finds the kernel image with the special format. And we can create it by mkimage tool that supported by u-boot:
```
MKIMAGE?=~/workspace/u-boot/tools/mkimage
$(MKIMAGE) -A arm64 -C none -O linux -T kernel -d $(BUILD_DIR)/kernel8.img -a 0x80000 -e 0x80000 $(BUILD_DIR)/kernel8.uimg
```
I close this issue.
