### ISSUE TITLE
Use kernel8.img naming convention

### ISSUE THREAD

**Issue by evopen** [s-matyukevich/raspberry-pi-os#40]
Pi 3 supports the kernel8.img naming convention. [Here](https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md)

I think by using kernel8.img, we can drop the arm_control flag (I drop it, turns out ok). 
After all we have ARMv8. And arm_control is actually undocumented.

**Comment by s-matyukevich** [comment]
This makes sense, I'll update the doc and Makefile

**Comment by evopen** [comment]
@s-matyukevich I can make pr if you like. But I need confirmation that this naming thing works with raspberry pi 3. Because i own a 3 b+.

**Comment by s-matyukevich** [comment]
@evopen a PR would be perfect! I already tested kernel.8 on my raspberry pi 3 b and it works fine.

In case you proceed with a PR please don't forget to update the Makefiles for all lessons and in the text of lesson 1 mention arm_controll flag as well - otherwise people might be confused when they see exercises based on old arm_control approach.

**Comment by s-matyukevich** [comment]
Done https://github.com/s-matyukevich/raspberry-pi-os/pull/59
